Repository chadrick-d-dev/sarah-chadrick-Rancid-Tomatillos, pull requests merged in 2020-12, with the labels that each got.

#2 Add movie data for iteration 1 and 2 of project
  src/movie-data.js
Labels: add Data

#9 Feature display movies
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.test.js
  src/MovieCard/MovieCard.css
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.test.js
  src/MoviesContainer/MoviesContainer.css
  src/MoviesContainer/MoviesContainer.js
  src/MoviesContainer/MoviesContainer.test.js
  src/SingleMovie/SingleMovie.css
  src/SingleMovie/SingleMovie.js
  src/SingleMovie/SingleMovie.test.js
  src/index.js
Labels: Iteration 1, JSX, React, SCSS, enhancement

#13 Feature/display single movie
  src/App/App.js
  src/Header/Header.css
  src/MovieCard/MovieCard.css
  src/MovieCard/MovieCard.js
  src/MoviesContainer/MoviesContainer.js
  src/SingleMovie/SingleMovie.css
  src/SingleMovie/SingleMovie.js
Labels: CSS, Iteration 2, JSX, React, enhancement

#24 Feature/pseudocode unit tests
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.test.js
  src/MovieCard/MovieCard.test.js
  src/MoviesContainer/MoviesContainer.js
  src/MoviesContainer/MoviesContainer.test.js
  src/SingleMovie/SingleMovie.js
  src/SingleMovie/SingleMovie.test.js
Labels: Iteration 2

#25 Feature/fetch movie data
  src/App/App.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.test.js
  src/MoviesContainer/MoviesContainer.js
  src/SingleMovie/SingleMovie.js
  src/apiCalls.js
Labels: Iteration 3, api calls

#27 Testing/single movie
  src/SingleMovie/SingleMovie.test.js
Labels: Iteration 2, React, Testing

#26 Add tests for movie card component
  src/MovieCard/MovieCard.test.js
Labels: Iteration 3, React, Testing

#29 Write and run passing unit testing for header
  src/App/App.test.js
  src/Header/Header.test.js
Labels: Iteration 3, React, Testing

#30 Testing/movie container
  src/App/App.js
  src/Header/Header.test.js
  src/MovieCard/MovieCard.test.js
  src/MoviesContainer/MoviesContainer.js
  src/MoviesContainer/MoviesContainer.test.js
Labels: Iteration 3, React, Testing

#31 Testing/app
  src/App/App.test.js
Labels: Iteration 3, React, Testing

#36 Refactor/router single movie
  package-lock.json
  package.json
  src/App/App.js
  src/MovieCard/MovieCard.css
  src/MovieCard/MovieCard.js
  src/MoviesContainer/MoviesContainer.js
  src/SingleMovie/SingleMovie.css
  src/SingleMovie/SingleMovie.js
  src/index.js
Labels: Iteration 4, React, Router

#37 Refactor/router testing
  src/App/App.test.js
  src/MovieCard/MovieCard.test.js
  src/MoviesContainer/MoviesContainer.test.js
  src/SingleMovie/SingleMovie.test.js
Labels: Iteration 4, React, Router, Testing

#39 feature/error-handling
  src/App/App.js
  src/App/App.test.js
  src/Error/Error.css
  src/Error/Error.js
  src/Error/Error.test.js
  src/SingleMovie/SingleMovie.js
Labels: Iteration 3, React, Testing, api calls

#43 Feature/error handling
  src/Error/Error.css
  src/Error/Error.js
  src/Error/Error.test.js
  src/SingleMovie/SingleMovie.js
  src/apiCalls.js
Labels: CSS, Iteration 3, React, Router, Testing, api calls

#44 Feature/search by rating
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.css
  src/MovieCard/MovieCard.css
  src/MovieCard/MovieCard.js
  src/MoviesContainer/MoviesContainer.css
  src/MoviesContainer/MoviesContainer.js
  src/MoviesContainer/MoviesContainer.test.js
  src/RatingSearch/RatingSearch.css
  src/RatingSearch/RatingSearch.js
  src/RatingSearch/RatingSearch.test.js
  src/SingleMovie/SingleMovie.css
  src/SingleMovie/SingleMovie.js
  src/SingleMovie/SingleMovie.test.js
  src/apiCalls.js
  src/index.js
Labels: CSS, Iteration 5, JSX, React, Router, Testing

#45 Update homepage path for deployment
  src/App/App.js
  src/RatingSearch/RatingSearch.js
  src/SingleMovie/SingleMovie.js
Labels: Iteration 5, enhancement
